// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// GolioAPIRouter defines the required methods for binding the api requests to a responses for the GolioAPI
// The GolioAPIRouter implementation should parse necessary information from the http request,
// pass the data to a GolioAPIServicer to perform the required actions, then write the service results to the http response.
type GolioAPIRouter interface { 
	ArticleTagsGet(http.ResponseWriter, *http.Request)
	ArticleTagsPost(http.ResponseWriter, *http.Request)
	ArticleTagsTagIdDelete(http.ResponseWriter, *http.Request)
	ArticleTagsTagIdPut(http.ResponseWriter, *http.Request)
	ArticlesAiPost(http.ResponseWriter, *http.Request)
	ArticlesArticleIdAiPut(http.ResponseWriter, *http.Request)
	ArticlesArticleIdGet(http.ResponseWriter, *http.Request)
	ArticlesArticleIdPut(http.ResponseWriter, *http.Request)
	ArticlesGet(http.ResponseWriter, *http.Request)
	ArticlesPost(http.ResponseWriter, *http.Request)
	EnglishDictionaryWordGet(http.ResponseWriter, *http.Request)
	HelloGet(http.ResponseWriter, *http.Request)
	MediaGet(http.ResponseWriter, *http.Request)
	MediaMediumIdDelete(http.ResponseWriter, *http.Request)
	MediaMediumIdGet(http.ResponseWriter, *http.Request)
	MediaPost(http.ResponseWriter, *http.Request)
	TranslationPost(http.ResponseWriter, *http.Request)
}


// GolioAPIServicer defines the api actions for the GolioAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GolioAPIServicer interface { 
	ArticleTagsGet(context.Context, string, int32, int32) (ImplResponse, error)
	ArticleTagsPost(context.Context, ArticleTagsPostRequest) (ImplResponse, error)
	ArticleTagsTagIdDelete(context.Context, string) (ImplResponse, error)
	ArticleTagsTagIdPut(context.Context, string, ArticleTagsTagIdPutRequest) (ImplResponse, error)
	ArticlesAiPost(context.Context, ArticlesAiPostRequest) (ImplResponse, error)
	ArticlesArticleIdAiPut(context.Context, string, ArticlesArticleIdAiPutRequest) (ImplResponse, error)
	ArticlesArticleIdGet(context.Context, string) (ImplResponse, error)
	ArticlesArticleIdPut(context.Context, string, ArticlesPostRequest) (ImplResponse, error)
	ArticlesGet(context.Context, int32, int32, string, []string) (ImplResponse, error)
	ArticlesPost(context.Context, ArticlesPostRequest) (ImplResponse, error)
	EnglishDictionaryWordGet(context.Context, string) (ImplResponse, error)
	HelloGet(context.Context) (ImplResponse, error)
	MediaGet(context.Context, int32, int32) (ImplResponse, error)
	MediaMediumIdDelete(context.Context, string) (ImplResponse, error)
	MediaMediumIdGet(context.Context, string) (ImplResponse, error)
	MediaPost(context.Context, MediaPostRequest) (ImplResponse, error)
	TranslationPost(context.Context, TranslationPostRequest) (ImplResponse, error)
}
