/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// AuthAPIRouter defines the required methods for binding the api requests to a responses for the AuthAPI
// The AuthAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AuthAPIServicer to perform the required actions, then write the service results to the http response.
type AuthAPIRouter interface { 
	JwtPost(http.ResponseWriter, *http.Request)
}
// GolioAPIRouter defines the required methods for binding the api requests to a responses for the GolioAPI
// The GolioAPIRouter implementation should parse necessary information from the http request,
// pass the data to a GolioAPIServicer to perform the required actions, then write the service results to the http response.
type GolioAPIRouter interface { 
	ArticlesArticleIdGet(http.ResponseWriter, *http.Request)
	ArticlesGet(http.ResponseWriter, *http.Request)
	ArticlesPost(http.ResponseWriter, *http.Request)
	ArticlesPut(http.ResponseWriter, *http.Request)
	HelloGet(http.ResponseWriter, *http.Request)
	JwtDelete(http.ResponseWriter, *http.Request)
	JwtPost(http.ResponseWriter, *http.Request)
	UserPost(http.ResponseWriter, *http.Request)
}


// AuthAPIServicer defines the api actions for the AuthAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthAPIServicer interface { 
	JwtPost(context.Context, JwtPostRequest) (ImplResponse, error)
}


// GolioAPIServicer defines the api actions for the GolioAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GolioAPIServicer interface { 
	ArticlesArticleIdGet(context.Context, string) (ImplResponse, error)
	ArticlesGet(context.Context, string, int32) (ImplResponse, error)
	ArticlesPost(context.Context, ArticlesPostRequest) (ImplResponse, error)
	ArticlesPut(context.Context, ArticlesPutRequest) (ImplResponse, error)
	HelloGet(context.Context) (ImplResponse, error)
	JwtDelete(context.Context) (ImplResponse, error)
	JwtPost(context.Context, JwtPostRequest) (ImplResponse, error)
	UserPost(context.Context) (ImplResponse, error)
}
