/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type MediaPostRequest struct {

	FileName string `json:"file_name"`
}

// AssertMediaPostRequestRequired checks if the required fields are not zero-ed
func AssertMediaPostRequestRequired(obj MediaPostRequest) error {
	elements := map[string]interface{}{
		"file_name": obj.FileName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMediaPostRequestConstraints checks if the values respects the defined constraints
func AssertMediaPostRequestConstraints(obj MediaPostRequest) error {
	return nil
}
