// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesPost200Response struct {

	Id string `json:"id"`
}

// AssertArticlesPost200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesPost200ResponseRequired(obj ArticlesPost200Response) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesPost200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesPost200ResponseConstraints(obj ArticlesPost200Response) error {
	return nil
}
