// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesArticleIdAiPut200Response struct {

	GeneratedBody string `json:"generated_body"`
}

// AssertArticlesArticleIdAiPut200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesArticleIdAiPut200ResponseRequired(obj ArticlesArticleIdAiPut200Response) error {
	elements := map[string]interface{}{
		"generated_body": obj.GeneratedBody,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesArticleIdAiPut200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesArticleIdAiPut200ResponseConstraints(obj ArticlesArticleIdAiPut200Response) error {
	return nil
}
