// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticleTag struct {

	Id string `json:"id"`

	Name string `json:"name"`
}

// AssertArticleTagRequired checks if the required fields are not zero-ed
func AssertArticleTagRequired(obj ArticleTag) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticleTagConstraints checks if the values respects the defined constraints
func AssertArticleTagConstraints(obj ArticleTag) error {
	return nil
}
