/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesGet200ResponseArticlesInner struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}

// AssertArticlesGet200ResponseArticlesInnerRequired checks if the required fields are not zero-ed
func AssertArticlesGet200ResponseArticlesInnerRequired(obj ArticlesGet200ResponseArticlesInner) error {
	return nil
}

// AssertArticlesGet200ResponseArticlesInnerConstraints checks if the values respects the defined constraints
func AssertArticlesGet200ResponseArticlesInnerConstraints(obj ArticlesGet200ResponseArticlesInner) error {
	return nil
}
