// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type InsertArticleTagResponse struct {

	Id string `json:"id"`
}

// AssertInsertArticleTagResponseRequired checks if the required fields are not zero-ed
func AssertInsertArticleTagResponseRequired(obj InsertArticleTagResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInsertArticleTagResponseConstraints checks if the values respects the defined constraints
func AssertInsertArticleTagResponseConstraints(obj InsertArticleTagResponse) error {
	return nil
}
