// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type TasksIdGet200Response struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Detail string `json:"detail"`

	StartTime *time.Time `json:"start_time,omitempty"`

	DueTime *time.Time `json:"due_time,omitempty"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}

// AssertTasksIdGet200ResponseRequired checks if the required fields are not zero-ed
func AssertTasksIdGet200ResponseRequired(obj TasksIdGet200Response) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"title": obj.Title,
		"detail": obj.Detail,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTasksIdGet200ResponseConstraints checks if the values respects the defined constraints
func AssertTasksIdGet200ResponseConstraints(obj TasksIdGet200Response) error {
	return nil
}
