// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesGet400Response struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}

// AssertArticlesGet400ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesGet400ResponseRequired(obj ArticlesGet400Response) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesGet400ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesGet400ResponseConstraints(obj ArticlesGet400Response) error {
	return nil
}
