/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesAiPost200Response struct {

	ArticleId string `json:"article_id"`
}

// AssertArticlesAiPost200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesAiPost200ResponseRequired(obj ArticlesAiPost200Response) error {
	elements := map[string]interface{}{
		"article_id": obj.ArticleId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesAiPost200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesAiPost200ResponseConstraints(obj ArticlesAiPost200Response) error {
	return nil
}
