/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesGet200ResponsePaging struct {

	Offset string `json:"offset"`
}

// AssertArticlesGet200ResponsePagingRequired checks if the required fields are not zero-ed
func AssertArticlesGet200ResponsePagingRequired(obj ArticlesGet200ResponsePaging) error {
	elements := map[string]interface{}{
		"offset": obj.Offset,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesGet200ResponsePagingConstraints checks if the values respects the defined constraints
func AssertArticlesGet200ResponsePagingConstraints(obj ArticlesGet200ResponsePaging) error {
	return nil
}
