// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type MediaGet200ResponseMediaInner struct {

	Id string `json:"id"`

	FileType string `json:"file_type"`

	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}

// AssertMediaGet200ResponseMediaInnerRequired checks if the required fields are not zero-ed
func AssertMediaGet200ResponseMediaInnerRequired(obj MediaGet200ResponseMediaInner) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"file_type": obj.FileType,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMediaGet200ResponseMediaInnerConstraints checks if the values respects the defined constraints
func AssertMediaGet200ResponseMediaInnerConstraints(obj MediaGet200ResponseMediaInner) error {
	return nil
}
