// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesGet200Response struct {

	Articles []Article `json:"articles"`

	Total int32 `json:"total"`
}

// AssertArticlesGet200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesGet200ResponseRequired(obj ArticlesGet200Response) error {
	elements := map[string]interface{}{
		"articles": obj.Articles,
		"total": obj.Total,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Articles {
		if err := AssertArticleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertArticlesGet200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesGet200ResponseConstraints(obj ArticlesGet200Response) error {
	for _, el := range obj.Articles {
		if err := AssertArticleConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
