// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type TranslationPost200Response struct {

	// 翻訳済みテキスト
	TranslatedText string `json:"translated_text"`
}

// AssertTranslationPost200ResponseRequired checks if the required fields are not zero-ed
func AssertTranslationPost200ResponseRequired(obj TranslationPost200Response) error {
	elements := map[string]interface{}{
		"translated_text": obj.TranslatedText,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTranslationPost200ResponseConstraints checks if the values respects the defined constraints
func AssertTranslationPost200ResponseConstraints(obj TranslationPost200Response) error {
	return nil
}
