/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type JwtPost404Response struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}

// AssertJwtPost404ResponseRequired checks if the required fields are not zero-ed
func AssertJwtPost404ResponseRequired(obj JwtPost404Response) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertJwtPost404ResponseConstraints checks if the values respects the defined constraints
func AssertJwtPost404ResponseConstraints(obj JwtPost404Response) error {
	return nil
}
