// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesAiPostRequest struct {

	// AIに対する命令のメッセージです
	Prompt string `json:"prompt"`
}

// AssertArticlesAiPostRequestRequired checks if the required fields are not zero-ed
func AssertArticlesAiPostRequestRequired(obj ArticlesAiPostRequest) error {
	elements := map[string]interface{}{
		"prompt": obj.Prompt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesAiPostRequestConstraints checks if the values respects the defined constraints
func AssertArticlesAiPostRequestConstraints(obj ArticlesAiPostRequest) error {
	return nil
}
