/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesGet200Response struct {

	Articles []ArticlesGet200ResponseArticlesInner `json:"articles"`

	Paging ArticlesGet200ResponsePaging `json:"paging"`
}

// AssertArticlesGet200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesGet200ResponseRequired(obj ArticlesGet200Response) error {
	elements := map[string]interface{}{
		"articles": obj.Articles,
		"paging": obj.Paging,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Articles {
		if err := AssertArticlesGet200ResponseArticlesInnerRequired(el); err != nil {
			return err
		}
	}
	if err := AssertArticlesGet200ResponsePagingRequired(obj.Paging); err != nil {
		return err
	}
	return nil
}

// AssertArticlesGet200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesGet200ResponseConstraints(obj ArticlesGet200Response) error {
	return nil
}
