/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Article struct {

	Id string `json:"id"`

	Title string `json:"title"`

	CreatedAt string `json:"created_at"`

	Tags []ArticleTag `json:"tags"`
}

// AssertArticleRequired checks if the required fields are not zero-ed
func AssertArticleRequired(obj Article) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"title": obj.Title,
		"created_at": obj.CreatedAt,
		"tags": obj.Tags,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Tags {
		if err := AssertArticleTagRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertArticleConstraints checks if the values respects the defined constraints
func AssertArticleConstraints(obj Article) error {
	return nil
}
