// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type HelloGet200Response struct {

	Hello string `json:"hello"`
}

// AssertHelloGet200ResponseRequired checks if the required fields are not zero-ed
func AssertHelloGet200ResponseRequired(obj HelloGet200Response) error {
	elements := map[string]interface{}{
		"hello": obj.Hello,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertHelloGet200ResponseConstraints checks if the values respects the defined constraints
func AssertHelloGet200ResponseConstraints(obj HelloGet200Response) error {
	return nil
}
