// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi


import (
	"fmt"
)



type LanguageCode string

// List of LanguageCode
const (
	AUTO LanguageCode = "auto"
	AF LanguageCode = "af"
	SQ LanguageCode = "sq"
	AM LanguageCode = "am"
	AR LanguageCode = "ar"
	HY LanguageCode = "hy"
	AZ LanguageCode = "az"
	BN LanguageCode = "bn"
	BS LanguageCode = "bs"
	BG LanguageCode = "bg"
	CA LanguageCode = "ca"
	ZH LanguageCode = "zh"
	ZH_TW LanguageCode = "zh-TW"
	HR LanguageCode = "hr"
	CS LanguageCode = "cs"
	DA LanguageCode = "da"
	FA_AF LanguageCode = "fa-AF"
	NL LanguageCode = "nl"
	EN LanguageCode = "en"
	ET LanguageCode = "et"
	FA LanguageCode = "fa"
	TL LanguageCode = "tl"
	FI LanguageCode = "fi"
	FR LanguageCode = "fr"
	FR_CA LanguageCode = "fr-CA"
	KA LanguageCode = "ka"
	DE LanguageCode = "de"
	EL LanguageCode = "el"
	GU LanguageCode = "gu"
	HT LanguageCode = "ht"
	HA LanguageCode = "ha"
	HE LanguageCode = "he"
	HI LanguageCode = "hi"
	HU LanguageCode = "hu"
	IS LanguageCode = "is"
	ID LanguageCode = "id"
	GA LanguageCode = "ga"
	IT LanguageCode = "it"
	JA LanguageCode = "ja"
	KN LanguageCode = "kn"
	KK LanguageCode = "kk"
	KO LanguageCode = "ko"
	LV LanguageCode = "lv"
	LT LanguageCode = "lt"
	MK LanguageCode = "mk"
	MS LanguageCode = "ms"
	ML LanguageCode = "ml"
	MT LanguageCode = "mt"
	MR LanguageCode = "mr"
	MN LanguageCode = "mn"
	NO LanguageCode = "no"
	PS LanguageCode = "ps"
	PL LanguageCode = "pl"
	PT LanguageCode = "pt"
	PT_PT LanguageCode = "pt-PT"
	PA LanguageCode = "pa"
	RO LanguageCode = "ro"
	RU LanguageCode = "ru"
	SR LanguageCode = "sr"
	SI LanguageCode = "si"
	SK LanguageCode = "sk"
	SL LanguageCode = "sl"
	SO LanguageCode = "so"
	ES LanguageCode = "es"
	ES_MX LanguageCode = "es-MX"
	SW LanguageCode = "sw"
	SV LanguageCode = "sv"
	TA LanguageCode = "ta"
	TE LanguageCode = "te"
	TH LanguageCode = "th"
	TR LanguageCode = "tr"
	UK LanguageCode = "uk"
	UR LanguageCode = "ur"
	UZ LanguageCode = "uz"
	VI LanguageCode = "vi"
	CY LanguageCode = "cy"
)

// AllowedLanguageCodeEnumValues is all the allowed values of LanguageCode enum
var AllowedLanguageCodeEnumValues = []LanguageCode{
	"auto",
	"af",
	"sq",
	"am",
	"ar",
	"hy",
	"az",
	"bn",
	"bs",
	"bg",
	"ca",
	"zh",
	"zh-TW",
	"hr",
	"cs",
	"da",
	"fa-AF",
	"nl",
	"en",
	"et",
	"fa",
	"tl",
	"fi",
	"fr",
	"fr-CA",
	"ka",
	"de",
	"el",
	"gu",
	"ht",
	"ha",
	"he",
	"hi",
	"hu",
	"is",
	"id",
	"ga",
	"it",
	"ja",
	"kn",
	"kk",
	"ko",
	"lv",
	"lt",
	"mk",
	"ms",
	"ml",
	"mt",
	"mr",
	"mn",
	"no",
	"ps",
	"pl",
	"pt",
	"pt-PT",
	"pa",
	"ro",
	"ru",
	"sr",
	"si",
	"sk",
	"sl",
	"so",
	"es",
	"es-MX",
	"sw",
	"sv",
	"ta",
	"te",
	"th",
	"tr",
	"uk",
	"ur",
	"uz",
	"vi",
	"cy",
}

// validLanguageCodeEnumValue provides a map of LanguageCodes for fast verification of use input
var validLanguageCodeEnumValues = map[LanguageCode]struct{}{
	"auto": {},
	"af": {},
	"sq": {},
	"am": {},
	"ar": {},
	"hy": {},
	"az": {},
	"bn": {},
	"bs": {},
	"bg": {},
	"ca": {},
	"zh": {},
	"zh-TW": {},
	"hr": {},
	"cs": {},
	"da": {},
	"fa-AF": {},
	"nl": {},
	"en": {},
	"et": {},
	"fa": {},
	"tl": {},
	"fi": {},
	"fr": {},
	"fr-CA": {},
	"ka": {},
	"de": {},
	"el": {},
	"gu": {},
	"ht": {},
	"ha": {},
	"he": {},
	"hi": {},
	"hu": {},
	"is": {},
	"id": {},
	"ga": {},
	"it": {},
	"ja": {},
	"kn": {},
	"kk": {},
	"ko": {},
	"lv": {},
	"lt": {},
	"mk": {},
	"ms": {},
	"ml": {},
	"mt": {},
	"mr": {},
	"mn": {},
	"no": {},
	"ps": {},
	"pl": {},
	"pt": {},
	"pt-PT": {},
	"pa": {},
	"ro": {},
	"ru": {},
	"sr": {},
	"si": {},
	"sk": {},
	"sl": {},
	"so": {},
	"es": {},
	"es-MX": {},
	"sw": {},
	"sv": {},
	"ta": {},
	"te": {},
	"th": {},
	"tr": {},
	"uk": {},
	"ur": {},
	"uz": {},
	"vi": {},
	"cy": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LanguageCode) IsValid() bool {
	_, ok := validLanguageCodeEnumValues[v]
	return ok
}

// NewLanguageCodeFromValue returns a pointer to a valid LanguageCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLanguageCodeFromValue(v string) (LanguageCode, error) {
	ev := LanguageCode(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for LanguageCode: valid values are %v", v, AllowedLanguageCodeEnumValues)
}



// AssertLanguageCodeRequired checks if the required fields are not zero-ed
func AssertLanguageCodeRequired(obj LanguageCode) error {
	return nil
}

// AssertLanguageCodeConstraints checks if the values respects the defined constraints
func AssertLanguageCodeConstraints(obj LanguageCode) error {
	return nil
}
