// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type WordDefinition struct {

	Definition string `json:"definition"`

	PartOfSpeech string `json:"part_of_speech"`

	Synonyms []string `json:"synonyms"`

	Antonyms []string `json:"antonyms"`

	Examples []string `json:"examples"`
}

// AssertWordDefinitionRequired checks if the required fields are not zero-ed
func AssertWordDefinitionRequired(obj WordDefinition) error {
	elements := map[string]interface{}{
		"definition": obj.Definition,
		"part_of_speech": obj.PartOfSpeech,
		"synonyms": obj.Synonyms,
		"antonyms": obj.Antonyms,
		"examples": obj.Examples,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertWordDefinitionConstraints checks if the values respects the defined constraints
func AssertWordDefinitionConstraints(obj WordDefinition) error {
	return nil
}
