/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesPutRequest struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Body string `json:"body"`
}

// AssertArticlesPutRequestRequired checks if the required fields are not zero-ed
func AssertArticlesPutRequestRequired(obj ArticlesPutRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"title": obj.Title,
		"body": obj.Body,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesPutRequestConstraints checks if the values respects the defined constraints
func AssertArticlesPutRequestConstraints(obj ArticlesPutRequest) error {
	return nil
}
