/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesPostRequest struct {

	Title string `json:"title"`

	Body string `json:"body"`
}

// AssertArticlesPostRequestRequired checks if the required fields are not zero-ed
func AssertArticlesPostRequestRequired(obj ArticlesPostRequest) error {
	elements := map[string]interface{}{
		"title": obj.Title,
		"body": obj.Body,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesPostRequestConstraints checks if the values respects the defined constraints
func AssertArticlesPostRequestConstraints(obj ArticlesPostRequest) error {
	return nil
}
