/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ArticlesTagsGet200Response struct {

	Tags *[]ArticleTag `json:"tags"`
}

// AssertArticlesTagsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertArticlesTagsGet200ResponseRequired(obj ArticlesTagsGet200Response) error {
	elements := map[string]interface{}{
		"tags": obj.Tags,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.Tags != nil {
		for _, el := range *obj.Tags {
			if err := AssertArticleTagRequired(el); err != nil {
				return err
			}
		}
	}
	return nil
}

// AssertArticlesTagsGet200ResponseConstraints checks if the values respects the defined constraints
func AssertArticlesTagsGet200ResponseConstraints(obj ArticlesTagsGet200Response) error {
	return nil
}
