// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type ArticlesTagsTagIdPutRequest struct {

	Name string `json:"name"`
}

// AssertArticlesTagsTagIdPutRequestRequired checks if the required fields are not zero-ed
func AssertArticlesTagsTagIdPutRequestRequired(obj ArticlesTagsTagIdPutRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertArticlesTagsTagIdPutRequestConstraints checks if the values respects the defined constraints
func AssertArticlesTagsTagIdPutRequestConstraints(obj ArticlesTagsTagIdPutRequest) error {
	return nil
}
