// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * folio
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type TranslationPostRequest struct {

	SourceLanguageCode LanguageCode `json:"source_language_code"`

	TargetLanguageCode LanguageCode `json:"target_language_code"`

	// 翻訳するテキスト
	Text string `json:"text"`
}

// AssertTranslationPostRequestRequired checks if the required fields are not zero-ed
func AssertTranslationPostRequestRequired(obj TranslationPostRequest) error {
	elements := map[string]interface{}{
		"source_language_code": obj.SourceLanguageCode,
		"target_language_code": obj.TargetLanguageCode,
		"text": obj.Text,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTranslationPostRequestConstraints checks if the values respects the defined constraints
func AssertTranslationPostRequestConstraints(obj TranslationPostRequest) error {
	return nil
}
