/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type MediaMediumIdGet200Response struct {

	MediumId string `json:"medium_id"`

	ThumbnailUrl string `json:"thumbnail_url"`

	DownloadUrl string `json:"download_url"`

	FileType string `json:"file_type"`
}

// AssertMediaMediumIdGet200ResponseRequired checks if the required fields are not zero-ed
func AssertMediaMediumIdGet200ResponseRequired(obj MediaMediumIdGet200Response) error {
	elements := map[string]interface{}{
		"medium_id": obj.MediumId,
		"thumbnail_url": obj.ThumbnailUrl,
		"download_url": obj.DownloadUrl,
		"file_type": obj.FileType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMediaMediumIdGet200ResponseConstraints checks if the values respects the defined constraints
func AssertMediaMediumIdGet200ResponseConstraints(obj MediaMediumIdGet200Response) error {
	return nil
}
