/*
 * My Project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type MediaGet200Response struct {

	TotalCount int32 `json:"total_count"`

	Media []MediaGet200ResponseMediaInner `json:"media"`
}

// AssertMediaGet200ResponseRequired checks if the required fields are not zero-ed
func AssertMediaGet200ResponseRequired(obj MediaGet200Response) error {
	elements := map[string]interface{}{
		"total_count": obj.TotalCount,
		"media": obj.Media,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Media {
		if err := AssertMediaGet200ResponseMediaInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMediaGet200ResponseConstraints checks if the values respects the defined constraints
func AssertMediaGet200ResponseConstraints(obj MediaGet200Response) error {
	return nil
}
