openapi: 3.0.1
info:
  description: ""
  title: My Project
  version: 1.0.0
servers:
- url: /
tags:
- name: golio
paths:
  /articles:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        example: "0"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        example: "10"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    articles:
                    - id: 記事ID
                      title: 記事タイトル
                      created_at: 作成日
              schema:
                $ref: '#/components/schemas/_articles_get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事投稿
      tags:
      - golio
  /articles/{article_id}:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: 記事ID
                    title: 記事タイトル
                    body: 記事本文
              schema:
                $ref: '#/components/schemas/_articles__article_id__get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事取得
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事更新
      tags:
      - golio
  /hello:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    hello: world
              schema:
                $ref: '#/components/schemas/_hello_get_200_response'
          description: Success
      security: []
      summary: hello
      tags:
      - golio
  /media:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: メディア一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: メディアの登録
      tags:
      - golio
  /media/{medium_id}:
    delete:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: メディアの削除
      tags:
      - golio
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_media__medium_id__get_200_response'
          description: Success
      security: []
      summary: メディアの取得
      tags:
      - golio
components:
  schemas:
    _articles_get_200_response_articles_inner:
      example:
        created_at: created_at
        id: id
        title: title
      properties:
        id:
          type: string
        title:
          type: string
        created_at:
          type: string
      type: object
    _articles_get_200_response:
      example:
        total: 0
        articles:
        - created_at: created_at
          id: id
          title: title
        - created_at: created_at
          id: id
          title: title
      properties:
        articles:
          items:
            $ref: '#/components/schemas/_articles_get_200_response_articles_inner'
          type: array
        total:
          type: integer
      required:
      - articles
      - total
      type: object
    _articles_get_400_response:
      example:
        code: 6
        message: message
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    _articles_post_request:
      properties:
        title:
          type: string
        body:
          type: string
      required:
      - body
      - title
      type: object
    _articles__article_id__get_200_response:
      example:
        user_id: user_id
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        title: title
        body: body
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        created_at:
          format: date-time
          type: string
        user_id:
          type: string
      required:
      - body
      - created_at
      - id
      - title
      - user_id
      type: object
    _hello_get_200_response:
      example:
        hello: hello
      properties:
        hello:
          type: string
      required:
      - hello
      type: object
    _media__medium_id__get_200_response:
      example:
        file_type: file_type
        download_url: download_url
        medium_id: medium_id
        thumbnail_url: thumbnail_url
      properties:
        medium_id:
          type: string
        thumbnail_url:
          type: string
        download_url:
          type: string
        file_type:
          type: string
      required:
      - download_url
      - file_type
      - medium_id
      - thumbnail_url
      type: object
  securitySchemes: {}
