openapi: 3.0.1
info:
  description: ""
  title: My Project
  version: 1.0.0
servers:
- url: /
tags:
- name: golio
paths:
  /articles:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        example: "0"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        example: "10"
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: タイトルの検索
        explode: true
        in: query
        name: search_title_text
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    articles:
                    - id: 記事ID
                      title: 記事タイトル
                      created_at: 作成日
              schema:
                $ref: '#/components/schemas/_articles_get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: ""
              schema:
                $ref: '#/components/schemas/_articles_post_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事投稿
      tags:
      - golio
  /articles/{article_id}:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    id: 記事ID
                    title: 記事タイトル
                    body: 記事本文
              schema:
                $ref: '#/components/schemas/_articles__article_id__get_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事取得
      tags:
      - golio
    put:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事更新
      tags:
      - golio
  /articles/{article_id}/ai:
    put:
      deprecated: false
      description: AIに命令を下して、記事の内容の更新をするAPIです
      parameters:
      - description: ""
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              title: 記事タイトル
            schema:
              $ref: '#/components/schemas/_articles__article_id__ai_put_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    generated_body: ""
              schema:
                $ref: '#/components/schemas/_articles__article_id__ai_put_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事AI更新
      tags:
      - golio
  /articles/ai:
    post:
      deprecated: false
      description: AIに命令を下して、記事を作成するAPIです
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              prompt: ut eiusmod enim cillum
            schema:
              $ref: '#/components/schemas/_articles_ai_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    article_id: ""
              schema:
                $ref: '#/components/schemas/_articles_ai_post_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_articles_get_400_response'
          description: Invalid input
      security: []
      summary: 記事AI作成
      tags:
      - golio
  /hello:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    hello: world
              schema:
                $ref: '#/components/schemas/_hello_get_200_response'
          description: Success
      security: []
      summary: hello
      tags:
      - golio
  /media:
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: ""
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    total_count: 0
                    media:
                    - id: ""
                      file_type: ""
                      thumbnail_url: ""
                      created_at: ""
                      updated_at: ""
              schema:
                $ref: '#/components/schemas/_media_get_200_response'
          description: Success
      security: []
      summary: メディア一覧取得
      tags:
      - golio
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              file_name: ""
              file_type: ""
            schema:
              $ref: '#/components/schemas/_media_post_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: Success
                  value:
                    upload_presigned_url: ""
              schema:
                $ref: '#/components/schemas/_media_post_200_response'
          description: Success
      security: []
      summary: メディアの登録
      tags:
      - golio
  /media/{medium_id}:
    delete:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      security: []
      summary: メディアの削除
      tags:
      - golio
    get:
      deprecated: false
      description: ""
      parameters:
      - description: ""
        explode: false
        in: path
        name: medium_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_media__medium_id__get_200_response'
          description: Success
      security: []
      summary: メディアの取得
      tags:
      - golio
  /translation:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_translation_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_translation_post_200_response'
          description: Success
      security: []
      summary: 翻訳
      tags:
      - golio
components:
  schemas:
    language_code:
      enum:
      - auto
      - af
      - sq
      - am
      - ar
      - hy
      - az
      - bn
      - bs
      - bg
      - ca
      - zh
      - zh-TW
      - hr
      - cs
      - da
      - fa-AF
      - nl
      - en
      - et
      - fa
      - tl
      - fi
      - fr
      - fr-CA
      - ka
      - de
      - el
      - gu
      - ht
      - ha
      - he
      - hi
      - hu
      - is
      - id
      - ga
      - it
      - ja
      - kn
      - kk
      - ko
      - lv
      - lt
      - mk
      - ms
      - ml
      - mt
      - mr
      - mn
      - "no"
      - ps
      - pl
      - pt
      - pt-PT
      - pa
      - ro
      - ru
      - sr
      - si
      - sk
      - sl
      - so
      - es
      - es-MX
      - sw
      - sv
      - ta
      - te
      - th
      - tr
      - uk
      - ur
      - uz
      - vi
      - cy
      type: string
    _articles_get_200_response_articles_inner:
      example:
        created_at: created_at
        id: id
        title: title
      properties:
        id:
          type: string
        title:
          type: string
        created_at:
          type: string
      type: object
    _articles_get_200_response:
      example:
        total: 0
        articles:
        - created_at: created_at
          id: id
          title: title
        - created_at: created_at
          id: id
          title: title
      properties:
        articles:
          items:
            $ref: '#/components/schemas/_articles_get_200_response_articles_inner'
          type: array
        total:
          type: integer
      required:
      - articles
      - total
      type: object
    _articles_get_400_response:
      example:
        code: 6
        message: message
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    _articles_post_request:
      properties:
        title:
          type: string
        body:
          type: string
      required:
      - body
      - title
      type: object
    _articles_post_200_response:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    _articles__article_id__get_200_response:
      example:
        user_id: user_id
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        title: title
        body: body
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        created_at:
          format: date-time
          type: string
        user_id:
          type: string
      required:
      - body
      - created_at
      - id
      - title
      - user_id
      type: object
    _articles__article_id__ai_put_request:
      properties:
        message:
          description: AIに対する命令のメッセージです
          type: string
      required:
      - message
      type: object
    _articles__article_id__ai_put_200_response:
      example:
        generated_body: generated_body
      properties:
        generated_body:
          type: string
      required:
      - generated_body
      type: object
    _articles_ai_post_request:
      properties:
        prompt:
          description: AIに対する命令のメッセージです
          type: string
      required:
      - prompt
      type: object
    _articles_ai_post_200_response:
      example:
        article_id: article_id
      properties:
        article_id:
          type: string
      required:
      - article_id
      type: object
    _hello_get_200_response:
      example:
        hello: hello
      properties:
        hello:
          type: string
      required:
      - hello
      type: object
    _media_get_200_response_media_inner:
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        file_type: file_type
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
        thumbnail_url: http://example.com/aeiou
      properties:
        id:
          type: string
        file_type:
          type: string
        thumbnail_url:
          format: url
          nullable: true
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - created_at
      - file_type
      - id
      - updated_at
      type: object
    _media_get_200_response:
      example:
        total_count: 0
        media:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          file_type: file_type
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          thumbnail_url: http://example.com/aeiou
        - updated_at: 2000-01-23T04:56:07.000+00:00
          file_type: file_type
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
          thumbnail_url: http://example.com/aeiou
      properties:
        total_count:
          type: integer
        media:
          items:
            $ref: '#/components/schemas/_media_get_200_response_media_inner'
          type: array
      required:
      - media
      - total_count
      type: object
    _media_post_request:
      properties:
        file_name:
          type: string
      required:
      - file_name
      type: object
    _media_post_200_response:
      example:
        upload_presigned_url: upload_presigned_url
      properties:
        upload_presigned_url:
          type: string
      required:
      - upload_presigned_url
      type: object
    _media__medium_id__get_200_response:
      example:
        file_type: file_type
        download_url: download_url
        medium_id: medium_id
        thumbnail_url: thumbnail_url
      properties:
        medium_id:
          type: string
        thumbnail_url:
          type: string
        download_url:
          type: string
        file_type:
          type: string
      required:
      - download_url
      - file_type
      - medium_id
      - thumbnail_url
      type: object
    _translation_post_request:
      properties:
        source_language_code:
          $ref: '#/components/schemas/language_code'
        target_language_code:
          $ref: '#/components/schemas/language_code'
        text:
          description: 翻訳するテキスト
          type: string
      required:
      - source_language_code
      - target_language_code
      - text
      type: object
    _translation_post_200_response:
      example:
        translated_text: translated_text
      properties:
        translated_text:
          description: 翻訳済みテキスト
          type: string
      required:
      - translated_text
      type: object
  securitySchemes: {}
