/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InsertArticleTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsertArticleTagResponse{}

// InsertArticleTagResponse struct for InsertArticleTagResponse
type InsertArticleTagResponse struct {
	Id string `json:"id"`
}

type _InsertArticleTagResponse InsertArticleTagResponse

// NewInsertArticleTagResponse instantiates a new InsertArticleTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsertArticleTagResponse(id string) *InsertArticleTagResponse {
	this := InsertArticleTagResponse{}
	this.Id = id
	return &this
}

// NewInsertArticleTagResponseWithDefaults instantiates a new InsertArticleTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsertArticleTagResponseWithDefaults() *InsertArticleTagResponse {
	this := InsertArticleTagResponse{}
	return &this
}

// GetId returns the Id field value
func (o *InsertArticleTagResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InsertArticleTagResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InsertArticleTagResponse) SetId(v string) {
	o.Id = v
}

func (o InsertArticleTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsertArticleTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *InsertArticleTagResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsertArticleTagResponse := _InsertArticleTagResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInsertArticleTagResponse)

	if err != nil {
		return err
	}

	*o = InsertArticleTagResponse(varInsertArticleTagResponse)

	return err
}

type NullableInsertArticleTagResponse struct {
	value *InsertArticleTagResponse
	isSet bool
}

func (v NullableInsertArticleTagResponse) Get() *InsertArticleTagResponse {
	return v.value
}

func (v *NullableInsertArticleTagResponse) Set(val *InsertArticleTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInsertArticleTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInsertArticleTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsertArticleTagResponse(val *InsertArticleTagResponse) *NullableInsertArticleTagResponse {
	return &NullableInsertArticleTagResponse{value: val, isSet: true}
}

func (v NullableInsertArticleTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsertArticleTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


