/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticlesGet400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticlesGet400Response{}

// ArticlesGet400Response struct for ArticlesGet400Response
type ArticlesGet400Response struct {
	Code int32 `json:"code"`
	Message string `json:"message"`
}

type _ArticlesGet400Response ArticlesGet400Response

// NewArticlesGet400Response instantiates a new ArticlesGet400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticlesGet400Response(code int32, message string) *ArticlesGet400Response {
	this := ArticlesGet400Response{}
	this.Code = code
	this.Message = message
	return &this
}

// NewArticlesGet400ResponseWithDefaults instantiates a new ArticlesGet400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticlesGet400ResponseWithDefaults() *ArticlesGet400Response {
	this := ArticlesGet400Response{}
	return &this
}

// GetCode returns the Code field value
func (o *ArticlesGet400Response) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ArticlesGet400Response) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ArticlesGet400Response) SetCode(v int32) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *ArticlesGet400Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ArticlesGet400Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ArticlesGet400Response) SetMessage(v string) {
	o.Message = v
}

func (o ArticlesGet400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticlesGet400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ArticlesGet400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticlesGet400Response := _ArticlesGet400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticlesGet400Response)

	if err != nil {
		return err
	}

	*o = ArticlesGet400Response(varArticlesGet400Response)

	return err
}

type NullableArticlesGet400Response struct {
	value *ArticlesGet400Response
	isSet bool
}

func (v NullableArticlesGet400Response) Get() *ArticlesGet400Response {
	return v.value
}

func (v *NullableArticlesGet400Response) Set(val *ArticlesGet400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableArticlesGet400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableArticlesGet400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticlesGet400Response(val *ArticlesGet400Response) *NullableArticlesGet400Response {
	return &NullableArticlesGet400Response{value: val, isSet: true}
}

func (v NullableArticlesGet400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticlesGet400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


