/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleTag{}

// ArticleTag struct for ArticleTag
type ArticleTag struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type _ArticleTag ArticleTag

// NewArticleTag instantiates a new ArticleTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleTag(id string, name string) *ArticleTag {
	this := ArticleTag{}
	this.Id = id
	this.Name = name
	return &this
}

// NewArticleTagWithDefaults instantiates a new ArticleTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleTagWithDefaults() *ArticleTag {
	this := ArticleTag{}
	return &this
}

// GetId returns the Id field value
func (o *ArticleTag) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArticleTag) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArticleTag) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ArticleTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ArticleTag) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ArticleTag) SetName(v string) {
	o.Name = v
}

func (o ArticleTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ArticleTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleTag := _ArticleTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleTag)

	if err != nil {
		return err
	}

	*o = ArticleTag(varArticleTag)

	return err
}

type NullableArticleTag struct {
	value *ArticleTag
	isSet bool
}

func (v NullableArticleTag) Get() *ArticleTag {
	return v.value
}

func (v *NullableArticleTag) Set(val *ArticleTag) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleTag) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleTag(val *ArticleTag) *NullableArticleTag {
	return &NullableArticleTag{value: val, isSet: true}
}

func (v NullableArticleTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


