/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteArticleTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteArticleTagResponse{}

// DeleteArticleTagResponse struct for DeleteArticleTagResponse
type DeleteArticleTagResponse struct {
	Id string `json:"id"`
}

type _DeleteArticleTagResponse DeleteArticleTagResponse

// NewDeleteArticleTagResponse instantiates a new DeleteArticleTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteArticleTagResponse(id string) *DeleteArticleTagResponse {
	this := DeleteArticleTagResponse{}
	this.Id = id
	return &this
}

// NewDeleteArticleTagResponseWithDefaults instantiates a new DeleteArticleTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteArticleTagResponseWithDefaults() *DeleteArticleTagResponse {
	this := DeleteArticleTagResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteArticleTagResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteArticleTagResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteArticleTagResponse) SetId(v string) {
	o.Id = v
}

func (o DeleteArticleTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteArticleTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DeleteArticleTagResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteArticleTagResponse := _DeleteArticleTagResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteArticleTagResponse)

	if err != nil {
		return err
	}

	*o = DeleteArticleTagResponse(varDeleteArticleTagResponse)

	return err
}

type NullableDeleteArticleTagResponse struct {
	value *DeleteArticleTagResponse
	isSet bool
}

func (v NullableDeleteArticleTagResponse) Get() *DeleteArticleTagResponse {
	return v.value
}

func (v *NullableDeleteArticleTagResponse) Set(val *DeleteArticleTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteArticleTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteArticleTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteArticleTagResponse(val *DeleteArticleTagResponse) *NullableDeleteArticleTagResponse {
	return &NullableDeleteArticleTagResponse{value: val, isSet: true}
}

func (v NullableDeleteArticleTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteArticleTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


