/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Article type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Article{}

// Article struct for Article
type Article struct {
	Id string `json:"id"`
	Title string `json:"title"`
	CreatedAt string `json:"created_at"`
	Tags []ArticleTag `json:"tags"`
}

type _Article Article

// NewArticle instantiates a new Article object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticle(id string, title string, createdAt string, tags []ArticleTag) *Article {
	this := Article{}
	this.Id = id
	this.Title = title
	this.CreatedAt = createdAt
	this.Tags = tags
	return &this
}

// NewArticleWithDefaults instantiates a new Article object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleWithDefaults() *Article {
	this := Article{}
	return &this
}

// GetId returns the Id field value
func (o *Article) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Article) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Article) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *Article) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Article) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Article) SetTitle(v string) {
	o.Title = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Article) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Article) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Article) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetTags returns the Tags field value
func (o *Article) GetTags() []ArticleTag {
	if o == nil {
		var ret []ArticleTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *Article) GetTagsOk() ([]ArticleTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *Article) SetTags(v []ArticleTag) {
	o.Tags = v
}

func (o Article) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Article) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *Article) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"created_at",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticle := _Article{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticle)

	if err != nil {
		return err
	}

	*o = Article(varArticle)

	return err
}

type NullableArticle struct {
	value *Article
	isSet bool
}

func (v NullableArticle) Get() *Article {
	return v.value
}

func (v *NullableArticle) Set(val *Article) {
	v.value = val
	v.isSet = true
}

func (v NullableArticle) IsSet() bool {
	return v.isSet
}

func (v *NullableArticle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticle(val *Article) *NullableArticle {
	return &NullableArticle{value: val, isSet: true}
}

func (v NullableArticle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


