/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaPostRequest{}

// MediaPostRequest struct for MediaPostRequest
type MediaPostRequest struct {
	FileName string `json:"file_name"`
}

type _MediaPostRequest MediaPostRequest

// NewMediaPostRequest instantiates a new MediaPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaPostRequest(fileName string) *MediaPostRequest {
	this := MediaPostRequest{}
	this.FileName = fileName
	return &this
}

// NewMediaPostRequestWithDefaults instantiates a new MediaPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaPostRequestWithDefaults() *MediaPostRequest {
	this := MediaPostRequest{}
	return &this
}

// GetFileName returns the FileName field value
func (o *MediaPostRequest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *MediaPostRequest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *MediaPostRequest) SetFileName(v string) {
	o.FileName = v
}

func (o MediaPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_name"] = o.FileName
	return toSerialize, nil
}

func (o *MediaPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaPostRequest := _MediaPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaPostRequest)

	if err != nil {
		return err
	}

	*o = MediaPostRequest(varMediaPostRequest)

	return err
}

type NullableMediaPostRequest struct {
	value *MediaPostRequest
	isSet bool
}

func (v NullableMediaPostRequest) Get() *MediaPostRequest {
	return v.value
}

func (v *NullableMediaPostRequest) Set(val *MediaPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaPostRequest(val *MediaPostRequest) *NullableMediaPostRequest {
	return &NullableMediaPostRequest{value: val, isSet: true}
}

func (v NullableMediaPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


