/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticlesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticlesPost200Response{}

// ArticlesPost200Response struct for ArticlesPost200Response
type ArticlesPost200Response struct {
	Id string `json:"id"`
}

type _ArticlesPost200Response ArticlesPost200Response

// NewArticlesPost200Response instantiates a new ArticlesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticlesPost200Response(id string) *ArticlesPost200Response {
	this := ArticlesPost200Response{}
	this.Id = id
	return &this
}

// NewArticlesPost200ResponseWithDefaults instantiates a new ArticlesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticlesPost200ResponseWithDefaults() *ArticlesPost200Response {
	this := ArticlesPost200Response{}
	return &this
}

// GetId returns the Id field value
func (o *ArticlesPost200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArticlesPost200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArticlesPost200Response) SetId(v string) {
	o.Id = v
}

func (o ArticlesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticlesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ArticlesPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticlesPost200Response := _ArticlesPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticlesPost200Response)

	if err != nil {
		return err
	}

	*o = ArticlesPost200Response(varArticlesPost200Response)

	return err
}

type NullableArticlesPost200Response struct {
	value *ArticlesPost200Response
	isSet bool
}

func (v NullableArticlesPost200Response) Get() *ArticlesPost200Response {
	return v.value
}

func (v *NullableArticlesPost200Response) Set(val *ArticlesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableArticlesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableArticlesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticlesPost200Response(val *ArticlesPost200Response) *NullableArticlesPost200Response {
	return &NullableArticlesPost200Response{value: val, isSet: true}
}

func (v NullableArticlesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticlesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


