/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateArticleTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateArticleTagResponse{}

// UpdateArticleTagResponse struct for UpdateArticleTagResponse
type UpdateArticleTagResponse struct {
	Id string `json:"id"`
}

type _UpdateArticleTagResponse UpdateArticleTagResponse

// NewUpdateArticleTagResponse instantiates a new UpdateArticleTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateArticleTagResponse(id string) *UpdateArticleTagResponse {
	this := UpdateArticleTagResponse{}
	this.Id = id
	return &this
}

// NewUpdateArticleTagResponseWithDefaults instantiates a new UpdateArticleTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateArticleTagResponseWithDefaults() *UpdateArticleTagResponse {
	this := UpdateArticleTagResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateArticleTagResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateArticleTagResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateArticleTagResponse) SetId(v string) {
	o.Id = v
}

func (o UpdateArticleTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateArticleTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *UpdateArticleTagResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateArticleTagResponse := _UpdateArticleTagResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateArticleTagResponse)

	if err != nil {
		return err
	}

	*o = UpdateArticleTagResponse(varUpdateArticleTagResponse)

	return err
}

type NullableUpdateArticleTagResponse struct {
	value *UpdateArticleTagResponse
	isSet bool
}

func (v NullableUpdateArticleTagResponse) Get() *UpdateArticleTagResponse {
	return v.value
}

func (v *NullableUpdateArticleTagResponse) Set(val *UpdateArticleTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateArticleTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateArticleTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateArticleTagResponse(val *UpdateArticleTagResponse) *NullableUpdateArticleTagResponse {
	return &NullableUpdateArticleTagResponse{value: val, isSet: true}
}

func (v NullableUpdateArticleTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateArticleTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


