/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticlesArticleIdAiPut200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticlesArticleIdAiPut200Response{}

// ArticlesArticleIdAiPut200Response struct for ArticlesArticleIdAiPut200Response
type ArticlesArticleIdAiPut200Response struct {
	GeneratedBody string `json:"generated_body"`
}

type _ArticlesArticleIdAiPut200Response ArticlesArticleIdAiPut200Response

// NewArticlesArticleIdAiPut200Response instantiates a new ArticlesArticleIdAiPut200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticlesArticleIdAiPut200Response(generatedBody string) *ArticlesArticleIdAiPut200Response {
	this := ArticlesArticleIdAiPut200Response{}
	this.GeneratedBody = generatedBody
	return &this
}

// NewArticlesArticleIdAiPut200ResponseWithDefaults instantiates a new ArticlesArticleIdAiPut200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticlesArticleIdAiPut200ResponseWithDefaults() *ArticlesArticleIdAiPut200Response {
	this := ArticlesArticleIdAiPut200Response{}
	return &this
}

// GetGeneratedBody returns the GeneratedBody field value
func (o *ArticlesArticleIdAiPut200Response) GetGeneratedBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GeneratedBody
}

// GetGeneratedBodyOk returns a tuple with the GeneratedBody field value
// and a boolean to check if the value has been set.
func (o *ArticlesArticleIdAiPut200Response) GetGeneratedBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedBody, true
}

// SetGeneratedBody sets field value
func (o *ArticlesArticleIdAiPut200Response) SetGeneratedBody(v string) {
	o.GeneratedBody = v
}

func (o ArticlesArticleIdAiPut200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticlesArticleIdAiPut200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["generated_body"] = o.GeneratedBody
	return toSerialize, nil
}

func (o *ArticlesArticleIdAiPut200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"generated_body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticlesArticleIdAiPut200Response := _ArticlesArticleIdAiPut200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticlesArticleIdAiPut200Response)

	if err != nil {
		return err
	}

	*o = ArticlesArticleIdAiPut200Response(varArticlesArticleIdAiPut200Response)

	return err
}

type NullableArticlesArticleIdAiPut200Response struct {
	value *ArticlesArticleIdAiPut200Response
	isSet bool
}

func (v NullableArticlesArticleIdAiPut200Response) Get() *ArticlesArticleIdAiPut200Response {
	return v.value
}

func (v *NullableArticlesArticleIdAiPut200Response) Set(val *ArticlesArticleIdAiPut200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableArticlesArticleIdAiPut200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableArticlesArticleIdAiPut200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticlesArticleIdAiPut200Response(val *ArticlesArticleIdAiPut200Response) *NullableArticlesArticleIdAiPut200Response {
	return &NullableArticlesArticleIdAiPut200Response{value: val, isSet: true}
}

func (v NullableArticlesArticleIdAiPut200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticlesArticleIdAiPut200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


