/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticlesAiPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticlesAiPostRequest{}

// ArticlesAiPostRequest struct for ArticlesAiPostRequest
type ArticlesAiPostRequest struct {
	// AIに対する命令のメッセージです
	Prompt string `json:"prompt"`
}

type _ArticlesAiPostRequest ArticlesAiPostRequest

// NewArticlesAiPostRequest instantiates a new ArticlesAiPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticlesAiPostRequest(prompt string) *ArticlesAiPostRequest {
	this := ArticlesAiPostRequest{}
	this.Prompt = prompt
	return &this
}

// NewArticlesAiPostRequestWithDefaults instantiates a new ArticlesAiPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticlesAiPostRequestWithDefaults() *ArticlesAiPostRequest {
	this := ArticlesAiPostRequest{}
	return &this
}

// GetPrompt returns the Prompt field value
func (o *ArticlesAiPostRequest) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *ArticlesAiPostRequest) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *ArticlesAiPostRequest) SetPrompt(v string) {
	o.Prompt = v
}

func (o ArticlesAiPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticlesAiPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt"] = o.Prompt
	return toSerialize, nil
}

func (o *ArticlesAiPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticlesAiPostRequest := _ArticlesAiPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticlesAiPostRequest)

	if err != nil {
		return err
	}

	*o = ArticlesAiPostRequest(varArticlesAiPostRequest)

	return err
}

type NullableArticlesAiPostRequest struct {
	value *ArticlesAiPostRequest
	isSet bool
}

func (v NullableArticlesAiPostRequest) Get() *ArticlesAiPostRequest {
	return v.value
}

func (v *NullableArticlesAiPostRequest) Set(val *ArticlesAiPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableArticlesAiPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableArticlesAiPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticlesAiPostRequest(val *ArticlesAiPostRequest) *NullableArticlesAiPostRequest {
	return &NullableArticlesAiPostRequest{value: val, isSet: true}
}

func (v NullableArticlesAiPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticlesAiPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


