/*
folio

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArticleTagsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleTagsPostRequest{}

// ArticleTagsPostRequest struct for ArticleTagsPostRequest
type ArticleTagsPostRequest struct {
	Name string `json:"name"`
}

type _ArticleTagsPostRequest ArticleTagsPostRequest

// NewArticleTagsPostRequest instantiates a new ArticleTagsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleTagsPostRequest(name string) *ArticleTagsPostRequest {
	this := ArticleTagsPostRequest{}
	this.Name = name
	return &this
}

// NewArticleTagsPostRequestWithDefaults instantiates a new ArticleTagsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleTagsPostRequestWithDefaults() *ArticleTagsPostRequest {
	this := ArticleTagsPostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ArticleTagsPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ArticleTagsPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ArticleTagsPostRequest) SetName(v string) {
	o.Name = v
}

func (o ArticleTagsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleTagsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ArticleTagsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArticleTagsPostRequest := _ArticleTagsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArticleTagsPostRequest)

	if err != nil {
		return err
	}

	*o = ArticleTagsPostRequest(varArticleTagsPostRequest)

	return err
}

type NullableArticleTagsPostRequest struct {
	value *ArticleTagsPostRequest
	isSet bool
}

func (v NullableArticleTagsPostRequest) Get() *ArticleTagsPostRequest {
	return v.value
}

func (v *NullableArticleTagsPostRequest) Set(val *ArticleTagsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleTagsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleTagsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleTagsPostRequest(val *ArticleTagsPostRequest) *NullableArticleTagsPostRequest {
	return &NullableArticleTagsPostRequest{value: val, isSet: true}
}

func (v NullableArticleTagsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleTagsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


