/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticlesAiPost200Response
 */
export interface ArticlesAiPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ArticlesAiPost200Response
     */
    articleId: string;
}

/**
 * Check if a given object implements the ArticlesAiPost200Response interface.
 */
export function instanceOfArticlesAiPost200Response(value: object): boolean {
    if (!('articleId' in value)) return false;
    return true;
}

export function ArticlesAiPost200ResponseFromJSON(json: any): ArticlesAiPost200Response {
    return ArticlesAiPost200ResponseFromJSONTyped(json, false);
}

export function ArticlesAiPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlesAiPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'],
    };
}

export function ArticlesAiPost200ResponseToJSON(value?: ArticlesAiPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'article_id': value['articleId'],
    };
}

