/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesArticleIdAiPut200Response
 */
export interface ArticlesArticleIdAiPut200Response {
  /**
   *
   * @type {string}
   * @memberof ArticlesArticleIdAiPut200Response
   */
  generatedBody: string;
}

/**
 * Check if a given object implements the ArticlesArticleIdAiPut200Response interface.
 */
export function instanceOfArticlesArticleIdAiPut200Response(
  value: object,
): boolean {
  if (!("generatedBody" in value)) return false;
  return true;
}

export function ArticlesArticleIdAiPut200ResponseFromJSON(
  json: any,
): ArticlesArticleIdAiPut200Response {
  return ArticlesArticleIdAiPut200ResponseFromJSONTyped(json, false);
}

export function ArticlesArticleIdAiPut200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesArticleIdAiPut200Response {
  if (json == null) {
    return json;
  }
  return {
    generatedBody: json["generated_body"],
  };
}

export function ArticlesArticleIdAiPut200ResponseToJSON(
  value?: ArticlesArticleIdAiPut200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    generated_body: value["generatedBody"],
  };
}
