/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesPostRequest
 */
export interface ArticlesPostRequest {
  /**
   *
   * @type {string}
   * @memberof ArticlesPostRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ArticlesPostRequest
   */
  body: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ArticlesPostRequest
   */
  tagIds: Array<string>;
}

/**
 * Check if a given object implements the ArticlesPostRequest interface.
 */
export function instanceOfArticlesPostRequest(value: object): boolean {
  if (!("title" in value)) return false;
  if (!("body" in value)) return false;
  if (!("tagIds" in value)) return false;
  return true;
}

export function ArticlesPostRequestFromJSON(json: any): ArticlesPostRequest {
  return ArticlesPostRequestFromJSONTyped(json, false);
}

export function ArticlesPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesPostRequest {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    body: json["body"],
    tagIds: json["tag_ids"],
  };
}

export function ArticlesPostRequestToJSON(
  value?: ArticlesPostRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    title: value["title"],
    body: value["body"],
    tag_ids: value["tagIds"],
  };
}
