/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesAiPostRequest
 */
export interface ArticlesAiPostRequest {
  /**
   * AIに対する命令のメッセージです
   * @type {string}
   * @memberof ArticlesAiPostRequest
   */
  prompt: string;
}

/**
 * Check if a given object implements the ArticlesAiPostRequest interface.
 */
export function instanceOfArticlesAiPostRequest(value: object): boolean {
  if (!("prompt" in value)) return false;
  return true;
}

export function ArticlesAiPostRequestFromJSON(
  json: any,
): ArticlesAiPostRequest {
  return ArticlesAiPostRequestFromJSONTyped(json, false);
}

export function ArticlesAiPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesAiPostRequest {
  if (json == null) {
    return json;
  }
  return {
    prompt: json["prompt"],
  };
}

export function ArticlesAiPostRequestToJSON(
  value?: ArticlesAiPostRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    prompt: value["prompt"],
  };
}
