/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesPost200Response
 */
export interface ArticlesPost200Response {
  /**
   *
   * @type {string}
   * @memberof ArticlesPost200Response
   */
  id: string;
}

/**
 * Check if a given object implements the ArticlesPost200Response interface.
 */
export function instanceOfArticlesPost200Response(value: object): boolean {
  if (!("id" in value)) return false;
  return true;
}

export function ArticlesPost200ResponseFromJSON(
  json: any,
): ArticlesPost200Response {
  return ArticlesPost200ResponseFromJSONTyped(json, false);
}

export function ArticlesPost200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesPost200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
  };
}

export function ArticlesPost200ResponseToJSON(
  value?: ArticlesPost200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
  };
}
