/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesGet400Response
 */
export interface ArticlesGet400Response {
  /**
   *
   * @type {number}
   * @memberof ArticlesGet400Response
   */
  code: number;
  /**
   *
   * @type {string}
   * @memberof ArticlesGet400Response
   */
  message: string;
}

/**
 * Check if a given object implements the ArticlesGet400Response interface.
 */
export function instanceOfArticlesGet400Response(value: object): boolean {
  if (!("code" in value)) return false;
  if (!("message" in value)) return false;
  return true;
}

export function ArticlesGet400ResponseFromJSON(
  json: any,
): ArticlesGet400Response {
  return ArticlesGet400ResponseFromJSONTyped(json, false);
}

export function ArticlesGet400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesGet400Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    message: json["message"],
  };
}

export function ArticlesGet400ResponseToJSON(
  value?: ArticlesGet400Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    message: value["message"],
  };
}
