/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleTag } from './ArticleTag';
import {
    ArticleTagFromJSON,
    ArticleTagFromJSONTyped,
    ArticleTagToJSON,
} from './ArticleTag';

/**
 * 
 * @export
 * @interface ArticlesTagsGet200Response
 */
export interface ArticlesTagsGet200Response {
    /**
     * 
     * @type {Array<ArticleTag>}
     * @memberof ArticlesTagsGet200Response
     */
    tags: Array<ArticleTag>;
}

/**
 * Check if a given object implements the ArticlesTagsGet200Response interface.
 */
export function instanceOfArticlesTagsGet200Response(value: object): boolean {
    if (!('tags' in value)) return false;
    return true;
}

export function ArticlesTagsGet200ResponseFromJSON(json: any): ArticlesTagsGet200Response {
    return ArticlesTagsGet200ResponseFromJSONTyped(json, false);
}

export function ArticlesTagsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlesTagsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': ((json['tags'] as Array<any>).map(ArticleTagFromJSON)),
    };
}

export function ArticlesTagsGet200ResponseToJSON(value?: ArticlesTagsGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tags': ((value['tags'] as Array<any>).map(ArticleTagToJSON)),
    };
}

