/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticleTagsTagIdPutRequest
 */
export interface ArticleTagsTagIdPutRequest {
  /**
   *
   * @type {string}
   * @memberof ArticleTagsTagIdPutRequest
   */
  name: string;
}

/**
 * Check if a given object implements the ArticleTagsTagIdPutRequest interface.
 */
export function instanceOfArticleTagsTagIdPutRequest(value: object): boolean {
  if (!("name" in value)) return false;
  return true;
}

export function ArticleTagsTagIdPutRequestFromJSON(
  json: any,
): ArticleTagsTagIdPutRequest {
  return ArticleTagsTagIdPutRequestFromJSONTyped(json, false);
}

export function ArticleTagsTagIdPutRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticleTagsTagIdPutRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function ArticleTagsTagIdPutRequestToJSON(
  value?: ArticleTagsTagIdPutRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    name: value["name"],
  };
}
