/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesGet200ResponseArticlesInner
 */
export interface ArticlesGet200ResponseArticlesInner {
  /**
   *
   * @type {string}
   * @memberof ArticlesGet200ResponseArticlesInner
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ArticlesGet200ResponseArticlesInner
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ArticlesGet200ResponseArticlesInner
   */
  createdAt?: string;
}

/**
 * Check if a given object implements the ArticlesGet200ResponseArticlesInner interface.
 */
export function instanceOfArticlesGet200ResponseArticlesInner(
  value: object,
): boolean {
  return true;
}

export function ArticlesGet200ResponseArticlesInnerFromJSON(
  json: any,
): ArticlesGet200ResponseArticlesInner {
  return ArticlesGet200ResponseArticlesInnerFromJSONTyped(json, false);
}

export function ArticlesGet200ResponseArticlesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesGet200ResponseArticlesInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["title"] == null ? undefined : json["title"],
    createdAt: json["created_at"] == null ? undefined : json["created_at"],
  };
}

export function ArticlesGet200ResponseArticlesInnerToJSON(
  value?: ArticlesGet200ResponseArticlesInner | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    title: value["title"],
    created_at: value["createdAt"],
  };
}
