/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleTag
 */
export interface ArticleTag {
    /**
     * 
     * @type {string}
     * @memberof ArticleTag
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleTag
     */
    name: string;
}

/**
 * Check if a given object implements the ArticleTag interface.
 */
export function instanceOfArticleTag(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function ArticleTagFromJSON(json: any): ArticleTag {
    return ArticleTagFromJSONTyped(json, false);
}

export function ArticleTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ArticleTagToJSON(value?: ArticleTag | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

