/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticlesTagsPostRequest
 */
export interface ArticlesTagsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ArticlesTagsPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ArticlesTagsPostRequest interface.
 */
export function instanceOfArticlesTagsPostRequest(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function ArticlesTagsPostRequestFromJSON(json: any): ArticlesTagsPostRequest {
    return ArticlesTagsPostRequestFromJSONTyped(json, false);
}

export function ArticlesTagsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlesTagsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ArticlesTagsPostRequestToJSON(value?: ArticlesTagsPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

