/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticlesTagsTagIdPutRequest
 */
export interface ArticlesTagsTagIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ArticlesTagsTagIdPutRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ArticlesTagsTagIdPutRequest interface.
 */
export function instanceOfArticlesTagsTagIdPutRequest(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function ArticlesTagsTagIdPutRequestFromJSON(json: any): ArticlesTagsTagIdPutRequest {
    return ArticlesTagsTagIdPutRequestFromJSONTyped(json, false);
}

export function ArticlesTagsTagIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlesTagsTagIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ArticlesTagsTagIdPutRequestToJSON(value?: ArticlesTagsTagIdPutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

