/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ArticlesArticleIdGet200Response
 */
export interface ArticlesArticleIdGet200Response {
  /**
   *
   * @type {string}
   * @memberof ArticlesArticleIdGet200Response
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ArticlesArticleIdGet200Response
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ArticlesArticleIdGet200Response
   */
  body: string;
  /**
   *
   * @type {Date}
   * @memberof ArticlesArticleIdGet200Response
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof ArticlesArticleIdGet200Response
   */
  userId: string;
}

/**
 * Check if a given object implements the ArticlesArticleIdGet200Response interface.
 */
export function instanceOfArticlesArticleIdGet200Response(
  value: object,
): boolean {
  if (!("id" in value)) return false;
  if (!("title" in value)) return false;
  if (!("body" in value)) return false;
  if (!("createdAt" in value)) return false;
  if (!("userId" in value)) return false;
  return true;
}

export function ArticlesArticleIdGet200ResponseFromJSON(
  json: any,
): ArticlesArticleIdGet200Response {
  return ArticlesArticleIdGet200ResponseFromJSONTyped(json, false);
}

export function ArticlesArticleIdGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArticlesArticleIdGet200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    body: json["body"],
    createdAt: new Date(json["created_at"]),
    userId: json["user_id"],
  };
}

export function ArticlesArticleIdGet200ResponseToJSON(
  value?: ArticlesArticleIdGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    title: value["title"],
    body: value["body"],
    created_at: value["createdAt"].toISOString(),
    user_id: value["userId"],
  };
}
