/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteArticleTagResponse
 */
export interface DeleteArticleTagResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteArticleTagResponse
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteArticleTagResponse interface.
 */
export function instanceOfDeleteArticleTagResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function DeleteArticleTagResponseFromJSON(json: any): DeleteArticleTagResponse {
    return DeleteArticleTagResponseFromJSONTyped(json, false);
}

export function DeleteArticleTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteArticleTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteArticleTagResponseToJSON(value?: DeleteArticleTagResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

