/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LanguageCode = {
  Auto: "auto",
  Af: "af",
  Sq: "sq",
  Am: "am",
  Ar: "ar",
  Hy: "hy",
  Az: "az",
  Bn: "bn",
  Bs: "bs",
  Bg: "bg",
  Ca: "ca",
  Zh: "zh",
  ZhTw: "zh-TW",
  Hr: "hr",
  Cs: "cs",
  Da: "da",
  FaAf: "fa-AF",
  Nl: "nl",
  En: "en",
  Et: "et",
  Fa: "fa",
  Tl: "tl",
  Fi: "fi",
  Fr: "fr",
  FrCa: "fr-CA",
  Ka: "ka",
  De: "de",
  El: "el",
  Gu: "gu",
  Ht: "ht",
  Ha: "ha",
  He: "he",
  Hi: "hi",
  Hu: "hu",
  Is: "is",
  Id: "id",
  Ga: "ga",
  It: "it",
  Ja: "ja",
  Kn: "kn",
  Kk: "kk",
  Ko: "ko",
  Lv: "lv",
  Lt: "lt",
  Mk: "mk",
  Ms: "ms",
  Ml: "ml",
  Mt: "mt",
  Mr: "mr",
  Mn: "mn",
  No: "no",
  Ps: "ps",
  Pl: "pl",
  Pt: "pt",
  PtPt: "pt-PT",
  Pa: "pa",
  Ro: "ro",
  Ru: "ru",
  Sr: "sr",
  Si: "si",
  Sk: "sk",
  Sl: "sl",
  So: "so",
  Es: "es",
  EsMx: "es-MX",
  Sw: "sw",
  Sv: "sv",
  Ta: "ta",
  Te: "te",
  Th: "th",
  Tr: "tr",
  Uk: "uk",
  Ur: "ur",
  Uz: "uz",
  Vi: "vi",
  Cy: "cy",
} as const;
export type LanguageCode = (typeof LanguageCode)[keyof typeof LanguageCode];

export function instanceOfLanguageCode(value: any): boolean {
  return Object.values(LanguageCode).includes(value);
}

export function LanguageCodeFromJSON(json: any): LanguageCode {
  return LanguageCodeFromJSONTyped(json, false);
}

export function LanguageCodeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LanguageCode {
  return json as LanguageCode;
}

export function LanguageCodeToJSON(value?: LanguageCode | null): any {
  return value as any;
}
