/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MediaPostRequest
 */
export interface MediaPostRequest {
  /**
   *
   * @type {string}
   * @memberof MediaPostRequest
   */
  fileName: string;
}

/**
 * Check if a given object implements the MediaPostRequest interface.
 */
export function instanceOfMediaPostRequest(value: object): boolean {
  if (!("fileName" in value)) return false;
  return true;
}

export function MediaPostRequestFromJSON(json: any): MediaPostRequest {
  return MediaPostRequestFromJSONTyped(json, false);
}

export function MediaPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MediaPostRequest {
  if (json == null) {
    return json;
  }
  return {
    fileName: json["file_name"],
  };
}

export function MediaPostRequestToJSON(value?: MediaPostRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    file_name: value["fileName"],
  };
}
