/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MediaGet200ResponseMediaInner
 */
export interface MediaGet200ResponseMediaInner {
  /**
   *
   * @type {string}
   * @memberof MediaGet200ResponseMediaInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof MediaGet200ResponseMediaInner
   */
  fileType: string;
  /**
   *
   * @type {string}
   * @memberof MediaGet200ResponseMediaInner
   */
  thumbnailUrl?: string;
  /**
   *
   * @type {Date}
   * @memberof MediaGet200ResponseMediaInner
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof MediaGet200ResponseMediaInner
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the MediaGet200ResponseMediaInner interface.
 */
export function instanceOfMediaGet200ResponseMediaInner(
  value: object,
): boolean {
  if (!("id" in value)) return false;
  if (!("fileType" in value)) return false;
  if (!("createdAt" in value)) return false;
  if (!("updatedAt" in value)) return false;
  return true;
}

export function MediaGet200ResponseMediaInnerFromJSON(
  json: any,
): MediaGet200ResponseMediaInner {
  return MediaGet200ResponseMediaInnerFromJSONTyped(json, false);
}

export function MediaGet200ResponseMediaInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MediaGet200ResponseMediaInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    fileType: json["file_type"],
    thumbnailUrl:
      json["thumbnail_url"] == null ? undefined : json["thumbnail_url"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function MediaGet200ResponseMediaInnerToJSON(
  value?: MediaGet200ResponseMediaInner | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    file_type: value["fileType"],
    thumbnail_url: value["thumbnailUrl"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
