/* tslint:disable */
/* eslint-disable */
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TranslationPost200Response
 */
export interface TranslationPost200Response {
  /**
   * 翻訳済みテキスト
   * @type {string}
   * @memberof TranslationPost200Response
   */
  translatedText: string;
}

/**
 * Check if a given object implements the TranslationPost200Response interface.
 */
export function instanceOfTranslationPost200Response(value: object): boolean {
  if (!("translatedText" in value)) return false;
  return true;
}

export function TranslationPost200ResponseFromJSON(
  json: any,
): TranslationPost200Response {
  return TranslationPost200ResponseFromJSONTyped(json, false);
}

export function TranslationPost200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TranslationPost200Response {
  if (json == null) {
    return json;
  }
  return {
    translatedText: json["translated_text"],
  };
}

export function TranslationPost200ResponseToJSON(
  value?: TranslationPost200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    translated_text: value["translatedText"],
  };
}
