/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateArticleTagResponse
 */
export interface UpdateArticleTagResponse {
  /**
   *
   * @type {string}
   * @memberof UpdateArticleTagResponse
   */
  id: string;
}

/**
 * Check if a given object implements the UpdateArticleTagResponse interface.
 */
export function instanceOfUpdateArticleTagResponse(value: object): boolean {
  if (!("id" in value)) return false;
  return true;
}

export function UpdateArticleTagResponseFromJSON(
  json: any,
): UpdateArticleTagResponse {
  return UpdateArticleTagResponseFromJSONTyped(json, false);
}

export function UpdateArticleTagResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateArticleTagResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
  };
}

export function UpdateArticleTagResponseToJSON(
  value?: UpdateArticleTagResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
  };
}
