/* tslint:disable */
/* eslint-disable */
/**
 * folio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WordDefinition
 */
export interface WordDefinition {
  /**
   *
   * @type {string}
   * @memberof WordDefinition
   */
  definition: string;
  /**
   *
   * @type {string}
   * @memberof WordDefinition
   */
  partOfSpeech: string;
  /**
   *
   * @type {Array<string>}
   * @memberof WordDefinition
   */
  synonyms: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof WordDefinition
   */
  antonyms: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof WordDefinition
   */
  examples: Array<string>;
}

/**
 * Check if a given object implements the WordDefinition interface.
 */
export function instanceOfWordDefinition(value: object): boolean {
  if (!("definition" in value)) return false;
  if (!("partOfSpeech" in value)) return false;
  if (!("synonyms" in value)) return false;
  if (!("antonyms" in value)) return false;
  if (!("examples" in value)) return false;
  return true;
}

export function WordDefinitionFromJSON(json: any): WordDefinition {
  return WordDefinitionFromJSONTyped(json, false);
}

export function WordDefinitionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WordDefinition {
  if (json == null) {
    return json;
  }
  return {
    definition: json["definition"],
    partOfSpeech: json["part_of_speech"],
    synonyms: json["synonyms"],
    antonyms: json["antonyms"],
    examples: json["examples"],
  };
}

export function WordDefinitionToJSON(value?: WordDefinition | null): any {
  if (value == null) {
    return value;
  }
  return {
    definition: value["definition"],
    part_of_speech: value["partOfSpeech"],
    synonyms: value["synonyms"],
    antonyms: value["antonyms"],
    examples: value["examples"],
  };
}
