package model

type TranslateLanguageCode string

func (lc TranslateLanguageCode) ToPtrStr() *string {
	s := string(lc)
	return &s
}

const (
	Auto                           TranslateLanguageCode = "auto" // オートで推論する
	AfrikaansLanguageCode          TranslateLanguageCode = "af"
	AlbanianLanguageCode           TranslateLanguageCode = "sq"
	AmharicLanguageCode            TranslateLanguageCode = "am"
	ArabicLanguageCode             TranslateLanguageCode = "ar"
	ArmenianLanguageCode           TranslateLanguageCode = "hy"
	AzerbaijaniLanguageCode        TranslateLanguageCode = "az"
	BengaliLanguageCode            TranslateLanguageCode = "bn"
	BosnianLanguageCode            TranslateLanguageCode = "bs"
	BulgarianLanguageCode          TranslateLanguageCode = "bg"
	CatalanLanguageCode            TranslateLanguageCode = "ca"
	ChineseSimplifiedLanguageCode  TranslateLanguageCode = "zh"
	ChineseTraditionalLanguageCode TranslateLanguageCode = "zh-TW"
	CroatianLanguageCode           TranslateLanguageCode = "hr"
	CzechLanguageCode              TranslateLanguageCode = "cs"
	DanishLanguageCode             TranslateLanguageCode = "da"
	DariLanguageCode               TranslateLanguageCode = "fa-AF"
	DutchLanguageCode              TranslateLanguageCode = "nl"
	EnglishLanguageCode            TranslateLanguageCode = "en"
	EstonianLanguageCode           TranslateLanguageCode = "et"
	FarsiPersianLanguageCode       TranslateLanguageCode = "fa"
	FilipinoTagalogLanguageCode    TranslateLanguageCode = "tl"
	FinnishLanguageCode            TranslateLanguageCode = "fi"
	FrenchLanguageCode             TranslateLanguageCode = "fr"
	FrenchCanadaLanguageCode       TranslateLanguageCode = "fr-CA"
	GeorgianLanguageCode           TranslateLanguageCode = "ka"
	GermanLanguageCode             TranslateLanguageCode = "de"
	GreekLanguageCode              TranslateLanguageCode = "el"
	GujaratiLanguageCode           TranslateLanguageCode = "gu"
	HaitianCreoleLanguageCode      TranslateLanguageCode = "ht"
	HausaLanguageCode              TranslateLanguageCode = "ha"
	HebrewLanguageCode             TranslateLanguageCode = "he"
	HindiLanguageCode              TranslateLanguageCode = "hi"
	HungarianLanguageCode          TranslateLanguageCode = "hu"
	IcelandicLanguageCode          TranslateLanguageCode = "is"
	IndonesianLanguageCode         TranslateLanguageCode = "id"
	IrishLanguageCode              TranslateLanguageCode = "ga"
	ItalianLanguageCode            TranslateLanguageCode = "it"
	JapaneseLanguageCode           TranslateLanguageCode = "ja"
	KannadaLanguageCode            TranslateLanguageCode = "kn"
	KazakhLanguageCode             TranslateLanguageCode = "kk"
	KoreanLanguageCode             TranslateLanguageCode = "ko"
	LatvianLanguageCode            TranslateLanguageCode = "lv"
	LithuanianLanguageCode         TranslateLanguageCode = "lt"
	MacedonianLanguageCode         TranslateLanguageCode = "mk"
	MalayLanguageCode              TranslateLanguageCode = "ms"
	MalayalamLanguageCode          TranslateLanguageCode = "ml"
	MalteseLanguageCode            TranslateLanguageCode = "mt"
	MarathiLanguageCode            TranslateLanguageCode = "mr"
	MongolianLanguageCode          TranslateLanguageCode = "mn"
	NorwegianBokmalLanguageCode    TranslateLanguageCode = "no"
	PashtoLanguageCode             TranslateLanguageCode = "ps"
	PolishLanguageCode             TranslateLanguageCode = "pl"
	PortugueseBrazilLanguageCode   TranslateLanguageCode = "pt"
	PortuguesePortugalLanguageCode TranslateLanguageCode = "pt-PT"
	PunjabiLanguageCode            TranslateLanguageCode = "pa"
	RomanianLanguageCode           TranslateLanguageCode = "ro"
	RussianLanguageCode            TranslateLanguageCode = "ru"
	SerbianLanguageCode            TranslateLanguageCode = "sr"
	SinhalaLanguageCode            TranslateLanguageCode = "si"
	SlovakLanguageCode             TranslateLanguageCode = "sk"
	SlovenianLanguageCode          TranslateLanguageCode = "sl"
	SomaliLanguageCode             TranslateLanguageCode = "so"
	SpanishLanguageCode            TranslateLanguageCode = "es"
	SpanishMexicoLanguageCode      TranslateLanguageCode = "es-MX"
	SwahiliLanguageCode            TranslateLanguageCode = "sw"
	SwedishLanguageCode            TranslateLanguageCode = "sv"
	TamilLanguageCode              TranslateLanguageCode = "ta"
	TeluguLanguageCode             TranslateLanguageCode = "te"
	ThaiLanguageCode               TranslateLanguageCode = "th"
	TurkishLanguageCode            TranslateLanguageCode = "tr"
	UkrainianLanguageCode          TranslateLanguageCode = "uk"
	UrduLanguageCode               TranslateLanguageCode = "ur"
	UzbekLanguageCode              TranslateLanguageCode = "uz"
	VietnameseLanguageCode         TranslateLanguageCode = "vi"
	WelshLanguageCode              TranslateLanguageCode = "cy"
)
