issues:
  exclude-dirs:
    - generated/*
  exclude-use-default: true
  exclude-case-sensitive: false
  exclude-dirs-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false
