version: "3.8"
services:
  s3:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=s3
      - HOSTNAME_EXTERNAL=s3
      - DEFAULT_REGION=ap-northeast-1
  s3-gui-client:
    image: cloudlena/s3manager:latest
    ports:
      - "14566:8080"
    environment:
      - ENDPOINT=s3:4566
      - ACCESS_KEY_ID=test
      - SECRET_ACCESS_KEY=test
      - USE_SSL=false
    depends_on:
      - s3
  s3-init:
    image: amazon/aws-cli
    depends_on:
      - s3
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
    entrypoint: /bin/sh -c
    command: >
     "
       aws --endpoint-url=http://s3:4566 s3api create-bucket --bucket golio-media --region ap-northeast-1 --create-bucket-configuration LocationConstraint=ap-northeast-1
     "
