name: deploy golio production
on:
    push:
        tags:
            - "golio/v?[0-9]+.[0-9]+.[0-9]+" 
        branches:
            - main
    # pull_request: # test
    #     types: [opened, synchronize]
    #     paths:
    #         - "golio/**.go"
        
permissions:
    id-token: write
    contents: read
jobs:
    deploy:
        uses: ./.github/workflows/deploy_golio.yml
        secrets:
            AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        with:
            repository: "production-golio"
            lambda_name: "production-golio-lambda"