name: deploy reolio production
on:
    push:
      branches:
        - main
      # tags:
        # - "reolio/v?[0-9]+.[0-9]+.[0-9]+" 
    # pull_request: # test
    #   types: [opened, synchronize]
    #   paths:
    #         - "reolio/**"

jobs:
    deploy:
        uses: ./.github/workflows/deploy_reolio.yml
        with:
          project_name: "reolio"
          # TODO github variablesに入れる
          golio_base_url: "https://35feqmh0xf.execute-api.ap-northeast-1.amazonaws.com/v1"
        secrets:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
