name: deploy reolio production
on:
    push:
      tags:
        - "reolio/v?[0-9]+.[0-9]+.[0-9]+" 

jobs:
    deploy:
        uses: ./.github/workflows/deploy_reolio.yml
        with:
          project_name: "reolio"
        secrets:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
