name: deploy reolio
on:
    workflow_call:
        inputs:
            project_name: 
                required: true
                type: string
            golio_base_url:
                required: true
                type: string
        secrets:
            CLOUDFLARE_API_TOKEN:
                required: true
            CLOUDFLARE_ACCOUNT_ID:
                required: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: reolio
        environment: 
            name: production
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            - run: npm install
            - run: npm run build
              env:
                REACT_APP_GOLIO_BASE_URL: ${{ inputs.golio_base_url }}

            - uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                command: pages deploy reolio/build --project-name=${{ inputs.project_name }} --commit-dirty=true
