name: deploy lime production
on:
    push:
        tags:
            - "lime/v?[0-9]+.[0-9]+.[0-9]+" 
        branches:
            - main
        paths:
            - "lime/**.go"
            - ".github/workflows/deploy_lime*"
        
permissions:
    id-token: write
    contents: read
jobs:
    deploy:
        uses: ./.github/workflows/deploy_lime.yml
        secrets:
            AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        with:
            repository: "production-lime"
            lambda_name: "production-lime-lambda"