name: Go Test
on:
    workflow_call:
        inputs:
            directory:
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.directory }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version-file: '${{ inputs.directory }}/go.mod'
                cache-dependency-path: '${{ inputs.directory }}'
            - run: go test ./... -cover
