name: React build and test 
on:
    workflow_call:
        inputs:
            directory:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.directory }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v2
              with:
                node-version: '20'
            - run: npm install
            - run: npm run build
